In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('res_csv.csv')

In [3]:
df

,source,created_at,lang,author_id,referenced_tweets/0/type,referenced_tweets/0/id,conversation_id,text,reply_settings,entities/urls/0/start,...,entities/hashtags/0/tag,entities/annotations/0/start,entities/annotations/0/end,entities/annotations/0/probability,entities/annotations/0/type,entities/annotations/0/normalized_text,entities/mentions/1/start,entities/mentions/1/end,entities/mentions/1/username,in_reply_to_user_id
0,Twitter Web App,2021-03-16T15:59:08+00:00,en,2244994945,quoted,1.370111e+18,1371853548762333187,Live now! https://t.co/sC2M3eRpPk,everyone,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Twitter Web App,2021-03-15T22:25:15+00:00,en,2244994945,quoted,1.370111e+18,1371588329368657923,Hope to see you tomorrow at 12 pm EST! \nhttps...,everyone,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Twitter Web App,2021-03-15T07:30:00+00:00,en,2244994945,quoted,1.367898e+18,1371363033352638467,üîé If you're using v2 full-archive search for A...,everyone,188.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Twitter Web App,2021-03-11T20:33:26+00:00,en,2244994945,NaN,NaN,1370110639545417729,"On Tuesday at 12 pm EST, @jessicagarson will c...",everyone,229.0,...,twitterapi,221.0,226.0,0.4652,Product,Twitch,NaN,NaN,NaN,NaN
4,Twitter Web App,2021-03-11T15:06:32+00:00,en,2244994945,replied_to,1.370028e+18,1370028371585814532,"‚ÄúI have been a developer from a young age,‚Äù sa...",everyone,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,73.0,marie_dm_,2.244995e+09